SELECT * FROM 

(SELECT CUST.[CUSTOMERID], B_LIST.T_AMT FROM

(SELECT [CUSTOMERID] FROM [Sales].[Customer]) AS CUST LEFT OUTER JOIN

(SELECT[CUSTOMERID], SUM([TOTALDUE]) AS T_AMT FROM[Sales].[SalesOrderHeader] GROUP BY [CustomerID]) AS B_LIST

ON CUST.[CustomerID] = B_LIST.[CUSTOMERID]) AS B_CUST WHERE T_AMT IS NULL

