SELECT GETDATE() AS DD_DATE, DATEPART(YY,GETDATE()) AS DD_YY, DATEPART(MM,GETDATE()) AS DD_MM, DATEPART(QQ,GETDATE()) AS DD_QQ

SELECT ModifiedDate, DATEPART(DD,ModifiedDate) AS DD_DD, DATEPART(HH,ModifiedDate) AS DD_HH, DATEPART(QQ, MODIFIEDDATE) AS DD_QQ 
FROM [Purchasing].[PurchaseOrderDetail]

SELECT*FROM [Purchasing].[PurchaseOrderDetail] WHERE DATEPART(YY,MODIFIEDDATE)=2013 AND DATEPART(MM,MODIFIEDDATE)=5

